import { useRef, useState } from "react";
import { api } from "../api/client";
const fields = ["employee_id", "first_name", "last_name", "email", "phone", "date_of_birth", "hire_date", "department", "employment_status", "manager_id", "source_system"];
export function NewMigration({ onCreated }: { onCreated: (batchId: string) => void }) {
  const [files, setFiles] = useState<File[]>([]); const [error, setError] = useState(""); const [busy, setBusy] = useState(false); const input = useRef<HTMLInputElement>(null);
  function choose(selected: File[]) { const invalid = selected.find((file) => !/\.(csv|xlsx)$/i.test(file.name)); setError(invalid ? `${invalid.name} is not a CSV or XLSX file.` : ""); setFiles(invalid ? [] : selected); }
  async function submit() { setBusy(true); setError(""); try { onCreated((await api.upload(files)).batch_id); } catch (reason) { setError(reason instanceof Error ? reason.message : "Upload failed"); } finally { setBusy(false); } }
  return <section aria-labelledby="new-title"><div className="section-heading"><div><p className="eyebrow">Start safely</p><h2 id="new-title">New migration</h2></div><p>Upload source exports together. Files are profiled and masked before mapping begins.</p></div><div className="split"><div className="panel"><button className="dropzone" type="button" onClick={() => input.current?.click()} onDragOver={(event) => event.preventDefault()} onDrop={(event) => { event.preventDefault(); choose([...event.dataTransfer.files]); }}><span className="drop-icon">↑</span><strong>Drop CSV or XLSX files</strong><span>or choose files from your computer</span></button><input ref={input} className="sr-only" aria-label="Choose employee files" type="file" multiple accept=".csv,.xlsx" onChange={(event) => choose([...(event.target.files ?? [])])} />{files.length > 0 && <ul className="file-list" aria-label="Selected files">{files.map((file) => <li key={file.name}><span>{file.name}</span><small>{(file.size / 1024).toFixed(1)} KB</small></li>)}</ul>}{error && <p role="alert" className="error">{error}</p>}<button className="primary" disabled={!files.length || busy} onClick={submit}>{busy ? "Creating…" : `Create migration${files.length ? ` (${files.length})` : ""}`}</button></div><aside className="panel schema"><p className="eyebrow">Target contract</p><h3>Employee</h3><ul>{fields.map((field, index) => <li key={field}><code>{field}</code>{index < 4 || [6,7,8].includes(index) ? <span>Required</span> : <span>Optional</span>}</li>)}</ul></aside></div></section>;
}

