import { useRef, useState } from "react";
import { api } from "../api/client";
const fields = ["employee_id", "first_name", "last_name", "email", "phone", "date_of_birth", "hire_date", "department", "employment_status", "manager_id", "source_system"];
export function NewMigration({ onCreated }: { onCreated: (batchId: string) => void }) {
  const [files, setFiles] = useState<File[]>([]); const [error, setError] = useState(""); const [busy, setBusy] = useState(false); const input = useRef<HTMLInputElement>(null);
  function choose(selected: File[]) { const invalid = selected.find((file) => !/\.(csv|xlsx)$/i.test(file.name)); setError(invalid ? `${invalid.name} is not supported. Choose a CSV (.csv) or Excel (.xlsx) file.` : ""); setFiles(invalid ? [] : selected); }
  async function submit() { setBusy(true); setError(""); try { onCreated((await api.upload(files)).batch_id); } catch (reason) { setError(reason instanceof Error ? reason.message : "Upload failed"); } finally { setBusy(false); } }
  return <section aria-labelledby="new-title"><div className="section-heading"><div><p className="eyebrow">Step 1 of 5</p><h2 id="new-title">Upload employee files</h2></div><p>Start with one or more source exports. MigrateFlow reads, profiles, and masks them before any model request.</p></div><ol className="workflow-guide" aria-label="Migration steps"><li className="current"><b>1</b><span><strong>Upload</strong><small>CSV or Excel</small></span></li><li><b>2</b><span><strong>Analyze</strong><small>Generate mappings</small></span></li><li><b>3</b><span><strong>Review</strong><small>Confirm uncertainty</small></span></li><li><b>4</b><span><strong>Preview</strong><small>Validate records</small></span></li><li><b>5</b><span><strong>Push</strong><small>Audit or roll back</small></span></li></ol><div className="format-notice"><strong>Supported input files</strong><span>CSV <code>.csv</code> and Excel <code>.xlsx</code>. Upload multiple files together when they belong to the same migration.</span></div><div className="split"><div className="panel"><button className="dropzone" type="button" onClick={() => input.current?.click()} onDragOver={(event) => event.preventDefault()} onDrop={(event) => { event.preventDefault(); choose([...event.dataTransfer.files]); }}><span className="drop-icon">↑</span><strong>Drop CSV or Excel files here</strong><span>Accepted: .csv and .xlsx</span><span>or choose files from your computer</span></button><input ref={input} className="sr-only" aria-label="Choose employee files" type="file" multiple accept=".csv,.xlsx" onChange={(event) => choose([...(event.target.files ?? [])])} />{files.length > 0 && <><p className="selection-summary"><strong>{files.length} file{files.length === 1 ? "" : "s"} selected</strong><span>Next: create the migration, then MigrateFlow will analyze the columns.</span></p><ul className="file-list" aria-label="Selected files">{files.map((file) => <li key={file.name}><span>{file.name}</span><small>{(file.size / 1024).toFixed(1)} KB</small></li>)}</ul></>}{error && <p role="alert" className="error">{error}</p>}<button className="primary" disabled={!files.length || busy} onClick={submit}>{busy ? "Reading and profiling files…" : `Continue to analysis${files.length ? ` (${files.length})` : ""}`}</button></div><aside className="panel schema"><p className="eyebrow">Destination fields</p><h3>Employee record</h3><p>Required fields must be present or reviewed before data can be pushed.</p><ul>{fields.map((field, index) => <li key={field}><code>{field}</code>{index < 4 || [6,7,8].includes(index) ? <span>Required</span> : <span>Optional</span>}</li>)}</ul></aside></div></section>;
}
